name: CI

on:
  workflow_dispatch:
 # push:
 #  branches: [main, "feature/**"]
 # pull_request:
 #   branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
